services:
  backend:
    build: ./backend
    image: bandres28/calendario-noticia-backend:latest
    container_name: calendario-noticia-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: bandres28/calendario-noticia-frontend:latest
    container_name: calendario-noticia-frontend
    ports:
      - "8080:80"
    environment:
      - API_URL=http://localhost:3000
    depends_on:
      - backend
    restart: unless-stopped
